#===============================================================================
# Docker Compose File zum einfachen Start aller Dienste
#===============================================================================
version: "3.9"

volumes:
    dbdata:
    dbconfig:

services:
    # MongoDB-Datenbank
    mongodb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: sensor_db
            MONGO_INITDB_ROOT_USERNAME: dbuser
            MONGO_INITDB_ROOT_PASSWORD: dbpass
        volumes:
            - dbdata:/data/db
            - dbconfig:/data/configdb

    # Admin-GUI für MongoDB
    mongo-gui:
        profiles:
            - dev
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
            ME_CONFIG_MONGODB_URL: mongodb://dbuser:dbpass@mongodb:27017/

    # MQTT-Server
    emqx:
        profiles:
            - mqtt
        image: emqx/emqx:latest
        ports:
            - 1883:1883
            - 18083:18083
        environment:
            EMQX_HOST: 0.0.0.0
            EMQX_DASHBOARD__DEFAULT_USERNAME: "admin"
            EMQX_DASHBOARD__DEFAULT_PASSWORD: "admin"

    # Python-Anwendung
    simple_logger:
        profiles:
            - prod
        build: ./SimpleLogger
        environment:
            MONGO_DB_CONNECTION: mongodb://dbuser:dbpass@mongodb:27017/
        depends_on:
            - mongodb